### ISSUE TITLE
overlay won't work ?

### ISSUE THREAD

**Issue by fastmatikqc** [tungyao/Nika-Windows#1]
hello to you and thank you for sharing (and no it is not detected) but indeed the mapper used is detected i edit 2 thing into with new CR3 for Fortnite and still safe Apex / Fortnite / Call Of Duty .

**the overlay is not finished? because it has no overlay in games thank you very much**

**Comment by tungyao** [comment]
black screen？

**Comment by tungyao** [comment]
you can check the `vals.hpp` `SENSE_VERBOS`, change it to `2`

**Comment by tungyao** [comment]
![image](https://github.com/user-attachments/assets/f28fbc8f-a734-482b-96b9-650e2b1359da)

overlay is running good, which your windows version

**Comment by fastmatikqc** [comment]
> ![image](https://private-user-images.githubusercontent.com/20518510/378471855-f28fbc8f-a734-482b-96b9-650e2b1359da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjU1MzUsIm5iZiI6MTcyOTUyNTIzNSwicGF0aCI6Ii8yMDUxODUxMC8zNzg0NzE4NTUtZjI4ZmJjOGYtYTczNC00ODJiLTk2YjktNjUwZTJiMTM1OWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE1NDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZmQyOGJjYTgzMWQ1ZjA1Njg5MTkzOGYzYWNlMGMzNDE3MmE1NTc3YTBlYTMyM2MyZmMyZDc4OTA1MTYwNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EipuP59gXh8Wet1YmrNQi71646NJc886ygsYTr--XTU)
> 
> overlay is running good, which your windows version

only see this in console Windows 10 22H2

**Comment by fastmatikqc** [comment]
dont say "Overlay Initialized!"
