### ISSUE TITLE
can you add triggerbot ?

### ISSUE THREAD

**Issue by fastmatikqc** [tungyao/Nika-Windows#2]
**this is from my other source Nika Windows ( without any overlay ) cant you implanted this into ur project thanks you a lot**

struct TriggerBot {
    ConfigLoader* cl;
    MyDisplay* display;
    LocalPlayer* lp;
    std::vector<Player*>* players;

    TriggerBot(ConfigLoader* configLoada, MyDisplay* myDisplay, LocalPlayer* localPlayer, std::vector<Player*>* all_players) {
        this->cl = configLoada;
        this->display = myDisplay;
        this->lp = localPlayer;
        this->players = all_players;
    }
    
    void shootAtEnemy(int counter) {
        if (!cl->FEATURE_TRIGGERBOT_ON || display->keyDown(cl->TRIGGERBOT_PAUSE_BUTTON)) return;
        if (!lp->isCombatReady()) return;
        
        int weaponId = lp->weaponIndex;
        //printf("Last weapon held: [%s] - id: [%d]- GrenadeID: [%d] - Ammo: [%d]\n", WeaponName(weaponId).c_str(), weaponId, lp->grenadeID, lp->ammoInClip);        
        if (
            weaponId != WEAPON_KRABER &&
            weaponId != WEAPON_P2020 &&
            weaponId != WEAPON_MOZAMBIQUE &&
            weaponId != WEAPON_EVA8 &&
            weaponId != WEAPON_PEACEKEEPER &&
            weaponId != WEAPON_MASTIFF &&
            weaponId != WEAPON_WINGMAN &&
            weaponId != WEAPON_LONGBOW &&
            weaponId != WEAPON_SENTINEL &&
            weaponId != WEAPON_G7 &&
            weaponId != WEAPON_HEMLOCK &&
            weaponId != WEAPON_3030 &&
            weaponId != WEAPON_TRIPLE_TAKE &&
            weaponId != WEAPON_BOCEK &&
            weaponId != WEAPON_THROWING_KNIFE
            )return;

        const float RANGE_MAX = (lp->inZoom) ? util::metersToGameUnits(cl->TRIGGERBOT_ZOOMED_RANGE) : util::metersToGameUnits(cl->TRIGGERBOT_HIPFIRE_RANGE);

        for (int i = 0; i < players->size(); i++) {
            Player* p = players->at(i);
            if (!p->isCombatReady()) continue;
            if (!p->enemy) continue;
            if (!p->aimedAt) continue;
            if (!p->visible) continue;
            
            if (p->distanceToLocalPlayer <= RANGE_MAX ) {
                mem::write<uint32_t>(OFF_REGION + OFF_IN_ATTACK + 0x8, 4);
                std::this_thread::sleep_for(std::chrono::milliseconds(1));
                mem::write<uint32_t>(OFF_REGION + OFF_IN_ATTACK + 0x8, 5);
                std::this_thread::sleep_for(std::chrono::milliseconds(1));
                mem::write<uint32_t>(OFF_REGION + OFF_IN_ATTACK + 0x8, 4);
                break;
            }
        }
    }
};

**Comment by tungyao** [comment]
there has autofire logic, in `AimBot.hpp` `280` line, just set correct AIMBOT_FIRING_KEY and replenish `myDisplay->kbPress`
![image](https://github.com/user-attachments/assets/630704aa-9f38-49cd-96d2-3abbe4551d3d)

**Comment by tungyao** [comment]
https://github.com/tungyao/Nika-Windows/commit/a47bcd8511b99e2d13464b2d16fc37f85d78d874

you can test it, i have no pc now

**Comment by fastmatikqc** [comment]
> there has autofire logic, in `AimBot.hpp` `280` line, just set correct AIMBOT_FIRING_KEY and replenish `myDisplay->kbPress` ![image](https://private-user-images.githubusercontent.com/20518510/379061916-630704aa-9f38-49cd-96d2-3abbe4551d3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODQxOTMsIm5iZiI6MTcyOTY4Mzg5MywicGF0aCI6Ii8yMDUxODUxMC8zNzkwNjE5MTYtNjMwNzA0YWEtOWYzOC00OWNkLTk2ZDItM2FiYmU0NTUxZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDExNDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NzNjZTYzNDMxYzE0ZGMzMDYzZTcwNWYyOTAxOTQ2Mzc4M2NmOTkxZjYyMGFhYjFmYzJhZmY4ZGEyZmNlMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8A-71MfMvvaD4eTuFiZCm_AJsyTUF6XwqApZZZhD8ns)

thanks you man ur are legends 😍

**Comment by Godofwar3323** [comment]
can you share driver source code

**Comment by tungyao** [comment]
> can you share driver source code

just normal CR3 rw driver
