### ISSUE TITLE
fked

### ISSUE THREAD

**Issue by xxZENxxx** [tungyao/Nika-Windows#4]
cr3 shuffle only DMA user !!

**Comment by tungyao** [comment]
did you solve the cr3 shuffle

**Comment by xxZENxxx** [comment]
> did you solve the cr3 shuffle

no yet, fixing it on memflow was harder than I expected

**Comment by fastmatikqcc** [comment]
> did you solve the cr3 shuffle

copy paste already thold you i have,,,,,,,,,,,,,,,,

struct cache {
	uintptr_t Address;
	MMPTE Value;
};
static cache cached_pml4e[512];
static cache cached_pdpte[512];
static cache cached_pde[512];
static cache cached_pte[512];

auto translate_linear(
	UINT64 directory_base,
	UINT64 address) -> UINT64 {
	_virt_addr_t virtual_address{};
	virtual_address.value = PVOID(address);
	SIZE_T Size = 0;

	if (cached_pml4e[virtual_address.pml4_index].Address != directory_base + 8 * virtual_address.pml4_index || !cached_pml4e[virtual_address.pml4_index].Value.u.Hard.Valid) {
		cached_pml4e[virtual_address.pml4_index].Address = directory_base + 8 * virtual_address.pml4_index;
		read_physical(PVOID(cached_pml4e[virtual_address.pml4_index].Address), reinterpret_cast<PVOID>(&cached_pml4e[virtual_address.pml4_index].Value), 8, &Size);
	}
	if (!cached_pml4e[virtual_address.pml4_index].Value.u.Hard.Valid)
		return 0;

	if (cached_pdpte[virtual_address.pdpt_index].Address != (cached_pml4e[virtual_address.pml4_index].Value.u.Hard.PageFrameNumber << 12) + 8 * virtual_address.pdpt_index || !cached_pdpte[virtual_address.pdpt_index].Value.u.Hard.Valid) {
		cached_pdpte[virtual_address.pdpt_index].Address = (cached_pml4e[virtual_address.pml4_index].Value.u.Hard.PageFrameNumber << 12) + 8 * virtual_address.pdpt_index;
		read_physical(PVOID(cached_pdpte[virtual_address.pdpt_index].Address), reinterpret_cast<PVOID>(&cached_pdpte[virtual_address.pdpt_index].Value), 8, &Size);
	}

	if (!cached_pdpte[virtual_address.pdpt_index].Value.u.Hard.Valid)
		return 0;

	if (cached_pde[virtual_address.pd_index].Address != (cached_pdpte[virtual_address.pdpt_index].Value.u.Hard.PageFrameNumber << 12) + 8 * virtual_address.pd_index || !cached_pde[virtual_address.pd_index].Value.u.Hard.Valid) {
		cached_pde[virtual_address.pd_index].Address = (cached_pdpte[virtual_address.pdpt_index].Value.u.Hard.PageFrameNumber << 12) + 8 * virtual_address.pd_index;
		read_physical(PVOID(cached_pde[virtual_address.pd_index].Address), reinterpret_cast<PVOID>(&cached_pde[virtual_address.pd_index].Value), 8, &Size);
	}
	if (!cached_pde[virtual_address.pd_index].Value.u.Hard.Valid)
		return 0;

	if (cached_pte[virtual_address.pt_index].Address != (cached_pde[virtual_address.pd_index].Value.u.Hard.PageFrameNumber << 12) + 8 * virtual_address.pt_index || !cached_pte[virtual_address.pt_index].Value.u.Hard.Valid) {
		cached_pte[virtual_address.pt_index].Address = (cached_pde[virtual_address.pd_index].Value.u.Hard.PageFrameNumber << 12) + 8 * virtual_address.pt_index;
		read_physical(PVOID(cached_pte[virtual_address.pt_index].Address), reinterpret_cast<PVOID>(&cached_pte[virtual_address.pt_index].Value), 8, &Size);
	}

	if (!cached_pte[virtual_address.pt_index].Value.u.Hard.Valid)
		return 0;

	return (cached_pte[virtual_address.pt_index].Value.u.Hard.PageFrameNumber << 12) + virtual_address.offset;
}

**Comment by tungyao** [comment]
> > did you solve the cr3 shuffle
> 
> **copy paste I already told you on discord that I have the CR3 shuffle , and this driver is beamed mean detected if you dont use right mapper .** [CR3 Shuffle Click-Here](https://github.com/fastmatikqcc/CR3_Shuffle)

thinks my bro, i knew it, i have look  new cr3 shuffle resolve in UC, i ready to fix translate_linear in that driver.

**Comment by xxZENxxx** [comment]
> > did you solve the cr3 shuffle
> 
> **copy paste I already told you on discord that I have the CR3 shuffle , and this driver is beamed mean detected if you dont use right mapper .** [CR3 Shuffle Click-Here](https://github.com/fastmatikqcc/CR3_Shuffle)

he talk about kvm i think is hard with memflow  i stack in  this issue XD

**Comment by tungyao** [comment]
yes, dma will dump all stack, maybe reflush every 5s. decrypt the key is best way

**Comment by xxZENxxx** [comment]
> yes, dma will dump all stack, maybe reflush every 5s. decrypt the key is best way

kvm will be fix  a soon problem sloved

**Comment by tungyao** [comment]
> > yes, dma will dump all stack, maybe reflush every 5s. decrypt the key is best way
> 
> kvm will be fix a soon problem sloved

good news

**Comment by tungyao** [comment]
im going to fix the dtb, i look a post in uc
